packages:
  - '.'

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 1440 # strictly enforced for security reasons
blockExoticSubdeps: true # prevents malicious packages from being installed